#!/usr/bin/python
# coding: utf-8

import subprocess
import os
import getpass

from device.scripts.util import ROOT_MESSAGE


def is_tool(package_name):   
    import apt
    # from apt import progress

    cache = apt.cache.Cache()
    # cache.update()
    cache.open()
    try:
        pkg = cache[package_name]
    except KeyError, e:
        print "{pkg_name}  not found".format(pkg_name=package_name)
        return False
    if pkg.is_installed:
        return True
    else:
        return False

user = getpass.getuser()
if  user != 'root':
    print ROOT_MESSAGE
    suffix = ' -s'
    # exit()
else:
    suffix = ''
doxy_version =''
if is_tool('doxygen'):
    print "Doxygen already installed"
else:
    subprocess.call(('apt-get install doxygen -s'+suffix).split(' '))

if is_tool('graphviz'):
    print "Graphviz already installed"
else:
    subprocess.call(('apt-get install graphviz dots -s'+suffix).split(' '))